In [1]:
'''This script load the hand postures data and defines various features on it
to create a linear dataset containing 13 features'''

__author__ = "Anjana Niranjan"
__email__ = "anjanani@usc.edu"

## Exploratory data analysis

Imports and raw data loading

In [2]:
import pandas as pd
import numpy as np

In [3]:
raw_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/mpr/D_train.csv')
raw_test = pd.read_csv('/content/drive/My Drive/Colab Notebooks/mpr/D_test.csv')

Checking the size and different columns in the train and test dfs to ensure they are the same

In [4]:
raw_train.shape

(13500, 39)

In [5]:
raw_test.shape

(21099, 39)

In [6]:
raw_train.columns

Index(['unnamed', 'Class', 'User', 'X0', 'Y0', 'Z0', 'X1', 'Y1', 'Z1', 'X2',
       'Y2', 'Z2', 'X3', 'Y3', 'Z3', 'X4', 'Y4', 'Z4', 'X5', 'Y5', 'Z5', 'X6',
       'Y6', 'Z6', 'X7', 'Y7', 'Z7', 'X8', 'Y8', 'Z8', 'X9', 'Y9', 'Z9', 'X10',
       'Y10', 'Z10', 'X11', 'Y11', 'Z11'],
      dtype='object')

In [7]:
raw_test.columns

Index(['Unnamed: 0', 'Class', 'User', 'X0', 'Y0', 'Z0', 'X1', 'Y1', 'Z1', 'X2',
       'Y2', 'Z2', 'X3', 'Y3', 'Z3', 'X4', 'Y4', 'Z4', 'X5', 'Y5', 'Z5', 'X6',
       'Y6', 'Z6', 'X7', 'Y7', 'Z7', 'X8', 'Y8', 'Z8', 'X9', 'Y9', 'Z9', 'X10',
       'Y10', 'Z10', 'X11', 'Y11', 'Z11'],
      dtype='object')

In [8]:
raw_train.head()

unnamed  Class  User         X0         Y0  ...  Y10  Z10  X11  Y11  Z11
0     1817      1     0  74.783715  43.948122  ...  NaN  NaN  NaN  NaN  NaN
1     6202      4     0   5.049161  64.413681  ...  NaN  NaN  NaN  NaN  NaN
2     7803      5     0  60.172219  82.358864  ...  NaN  NaN  NaN  NaN  NaN
3     4656      3     0  72.447893  49.526689  ...  NaN  NaN  NaN  NaN  NaN
4     6714      4     0  15.820552  68.284762  ...  NaN  NaN  NaN  NaN  NaN

[5 rows x 39 columns]

In [9]:
raw_test.head()

Unnamed: 0  Class  User         X0         Y0  ...  Y10  Z10  X11  Y11  Z11
0       56997      1    12  50.430805   4.296292  ...  NaN  NaN  NaN  NaN  NaN
1       56998      1    12  49.187604   4.615699  ...  NaN  NaN  NaN  NaN  NaN
2       56999      1    12  48.709604   4.750960  ...  NaN  NaN  NaN  NaN  NaN
3       57000      1    12  13.482479  81.850854  ...  NaN  NaN  NaN  NaN  NaN
4       57001      1    12  60.566446  69.583361  ...  NaN  NaN  NaN  NaN  NaN

[5 rows x 39 columns]

Getting the length and dtype info of the train and test data.

In [10]:
raw_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13500 entries, 0 to 13499
Data columns (total 39 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   unnamed  13500 non-null  int64  
 1   Class    13500 non-null  int64  
 2   User     13500 non-null  int64  
 3   X0       13500 non-null  float64
 4   Y0       13500 non-null  float64
 5   Z0       13500 non-null  float64
 6   X1       13500 non-null  float64
 7   Y1       13500 non-null  float64
 8   Z1       13500 non-null  float64
 9   X2       13500 non-null  float64
 10  Y2       13500 non-null  float64
 11  Z2       13500 non-null  float64
 12  X3       13464 non-null  float64
 13  Y3       13464 non-null  float64
 14  Z3       13464 non-null  float64
 15  X4       13254 non-null  float64
 16  Y4       13254 non-null  float64
 17  Z4       13254 non-null  float64
 18  X5       11363 non-null  float64
 19  Y5       11363 non-null  float64
 20  Z5       11363 non-null  float64
 21  X6       961

In [11]:
raw_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21099 entries, 0 to 21098
Data columns (total 39 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  21099 non-null  int64  
 1   Class       21099 non-null  int64  
 2   User        21099 non-null  int64  
 3   X0          21099 non-null  float64
 4   Y0          21099 non-null  float64
 5   Z0          21099 non-null  float64
 6   X1          21099 non-null  float64
 7   Y1          21099 non-null  float64
 8   Z1          21099 non-null  float64
 9   X2          21099 non-null  float64
 10  Y2          21099 non-null  float64
 11  Z2          21099 non-null  float64
 12  X3          20680 non-null  float64
 13  Y3          20680 non-null  float64
 14  Z3          20680 non-null  float64
 15  X4          19285 non-null  float64
 16  Y4          19285 non-null  float64
 17  Z4          19285 non-null  float64
 18  X5          17059 non-null  float64
 19  Y5          17059 non-nul

Summarizing the numerical values

In [12]:
raw_train.describe

<bound method NDFrame.describe of        unnamed  Class  User         X0          Y0  ...  Y10  Z10  X11  Y11  Z11
0         1817      1     0  74.783715   43.948122  ...  NaN  NaN  NaN  NaN  NaN
1         6202      4     0   5.049161   64.413681  ...  NaN  NaN  NaN  NaN  NaN
2         7803      5     0  60.172219   82.358864  ...  NaN  NaN  NaN  NaN  NaN
3         4656      3     0  72.447893   49.526689  ...  NaN  NaN  NaN  NaN  NaN
4         6714      4     0  15.820552   68.284762  ...  NaN  NaN  NaN  NaN  NaN
...        ...    ...   ...        ...         ...  ...  ...  ...  ...  ...  ...
13495    54247      4    11  52.222681   93.686787  ...  NaN  NaN  NaN  NaN  NaN
13496    56283      5    11  30.297470  152.306531  ...  NaN  NaN  NaN  NaN  NaN
13497    53767      4    11  92.561649   29.756399  ...  NaN  NaN  NaN  NaN  NaN
13498    49593      1    11  74.950069   79.675092  ...  NaN  NaN  NaN  NaN  NaN
13499    56438      5    11  82.221166   13.149745  ...  NaN  NaN  NaN  NaN

In [13]:
raw_test.describe

<bound method NDFrame.describe of        Unnamed: 0  Class  User         X0          Y0  ...  Y10  Z10  X11  Y11  Z11
0           56997      1    12  50.430805    4.296292  ...  NaN  NaN  NaN  NaN  NaN
1           56998      1    12  49.187604    4.615699  ...  NaN  NaN  NaN  NaN  NaN
2           56999      1    12  48.709604    4.750960  ...  NaN  NaN  NaN  NaN  NaN
3           57000      1    12  13.482479   81.850854  ...  NaN  NaN  NaN  NaN  NaN
4           57001      1    12  60.566446   69.583361  ...  NaN  NaN  NaN  NaN  NaN
...           ...    ...   ...        ...         ...  ...  ...  ...  ...  ...  ...
21094       78091      5    14  54.251127  129.177414  ...  NaN  NaN  NaN  NaN  NaN
21095       78092      5    14  54.334883  129.253842  ...  NaN  NaN  NaN  NaN  NaN
21096       78093      5    14  54.151540  129.269502  ...  NaN  NaN  NaN  NaN  NaN
21097       78094      5    14  27.915311  108.007390  ...  NaN  NaN  NaN  NaN  NaN
21098       78095      5    14  27.898705 

Checking for duplicates

In [14]:
raw_train.duplicated().sum()

0

In [15]:
raw_test.duplicated().sum()

0

#### From the above analysis, we can make the following conclusions:


1.   The training and the testing sets have 13 columns each
2.   There are many empty cells in both the dataframes
3.   There are no duplicate rows in the datasets
4.   This data cannot be directly used for modeling.




## Feature engineering

Making meaningful and usable linear data out of the raw data by defining 13 features:


1.   Mean of the x markers
2.   Mean of the y markers
3.   Mean of the z markers
4.   Std of the x markers
5.   Std of the y markers
6.   Std of the z markers
7.   Number of non 0 values in the data
8.   Minimum value of the x markers
9.   Minimum value of the y markers
10.   Minimum value of the z markers
11.  Maximum value of the x markers
12.  Maximum value of the y markers
13.  Maximum value of the z markers  



In [16]:
#Separating the X, Y and Z axis data
datax = raw_train[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11']]
datay = raw_train[['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10', 'Y11']]
dataz = raw_train[['Z0', 'Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'Z7', 'Z8', 'Z9', 'Z10', 'Z11']]
Class = raw_train['Class']

datax = np.array(datax)
datay = np.array(datay)
dataz = np.array(dataz)
Class = np.array(Class)

In [17]:
#Replacing the cells with no entries with 0
datax = np.nan_to_num(datax)
datay = np.nan_to_num(datay)
dataz = np.nan_to_num(dataz)

In [18]:
datax[0:10]

array([[ 74.78371485,  54.23312977,  35.02645154,  89.99802253,
         59.01827065,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  5.04916071,  22.51863481,  26.92855495, -14.66405118,
         48.78046722,  40.69286083,  -8.29461647,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 60.17221909,  56.61352091,  13.03216339,  77.104094  ,
        -14.20066886, -10.85987857,  47.80127924,  22.32655591,
         62.61321736,  79.04487197,   0.        ,   0.        ],
       [ 72.44789275,  77.64339666,  58.94276126,  57.15981917,
         47.93138108,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 15.82055163,  -4.13700887,  32.52449788,  52.95014644,
         43.98571972,  29.5743632 ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ -4.12135714,   4.9696368 ,

In [19]:
datax.shape

(13500, 12)

In [20]:
datay[0:10]

array([[ 43.94812205,  79.72823206,  88.67727892,  68.18921034,
         13.7954056 ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 64.41368088, 137.1762527 ,  94.92661587,  56.0034308 ,
         94.40494011, 134.954863  ,  34.89623704,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 82.35886375,  57.34830746, 132.025198  , 130.6575268 ,
        127.8000326 ,  98.72164114,  27.21449252, 105.226483  ,
        100.2307765 ,  90.99386301,   0.        ,   0.        ],
       [ 49.52668881,  75.41137977,  15.50448942,  92.0788088 ,
        135.4081316 ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 68.28476173,  56.90181493,  94.68646193,  97.23302698,
        137.1881027 , 140.2539604 ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [ 31.5541283 ,  67.77187716,

In [21]:
datay.shape

(13500, 12)

In [22]:
dataz[0:10]

array([[-75.61229137, -59.67420979, -48.21913512, -72.53829696,
        -71.1411728 ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-63.36922861, -78.38714836, -41.86302178, -60.82984696,
        -44.79770569, -60.81053035, -95.51368341,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-96.09745095, -90.71651151, -39.75175177, -51.98889523,
        -31.23126645,  -0.53579763, -78.09438601,   7.82026413,
         -1.87027677, -27.30629171,   0.        ,   0.        ],
       [-71.78535802, -71.27790606, -70.52985295, -33.91631133,
        -43.26036211,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-60.49815021, -62.68593229, -36.9767626 , -32.01556824,
        -50.90122041, -69.91392054,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-98.68842698, -62.22115205,

In [23]:
dataz.shape

(13500, 12)

In [24]:
x_mean = []
y_mean = []
z_mean = []
x_std = []
y_std = []
z_std = []
number = []

for i in range (13500):
  x_mean.append(np.mean(datax[i]))
  y_mean.append(np.mean(datay[i]))
  z_mean.append(np.mean(dataz[i]))
  x_std.append(np.std(datax[i]))
  y_std.append(np.std(datay[i]))
  z_std.append(np.std(dataz[i]))
  number.append(np.count_nonzero([datax[i], datay[i], dataz[i]]))

In [25]:
#Feature 1 - mean of x-axis values
x_mean = np.array(x_mean) 
x_mean

array([26.08829911, 10.08425091, 32.80394787, ..., 35.18024472,
       24.43492902, 25.48479356])

In [26]:
#Feature 2 - mean of y-axis values
y_mean = np.array(y_mean) 
y_mean

array([24.52818741, 51.3980017 , 79.38143206, ..., 46.50764602,
       37.56558859, 79.696158  ])

In [27]:
#Feature 3 - mean of z-axis values
z_mean = np.array(z_mean) 
z_mean

array([-27.2654255 , -37.13093043, -34.14769699, ..., -12.85172156,
       -21.19876915, -24.16483386])

In [28]:
#Feature 4 - standard deviation of x-axis values
x_std = np.array(x_std) 
x_std

array([33.13645626, 19.05409531, 33.29041087, ..., 38.96402541,
       30.73391735, 40.30659869])

In [29]:
#Feature 5 - standard deviation of y-axis values
y_std = np.array(y_std) 
y_std

array([33.87745822, 51.44227625, 45.80307094, ..., 54.13662984,
       42.93766674, 51.44891905])

In [30]:
#Feature 6 - standard deviation of z-axis values
z_std = np.array(z_std) 
z_std

array([32.92079481, 34.02956295, 36.10075052, ..., 27.06603722,
       23.62265384, 23.27841825])

In [31]:
#Feature 7 - number of data points present
number = np.array(number) 
number

array([15, 21, 30, ..., 21, 18, 30])

In [32]:
#Feature 8 - min x-axis value
x_min = (np.amin(datax, axis = 1)).T 
x_min

array([  0.        , -14.66405118, -14.20066886, ...,   0.        ,
         0.        , -30.54030433])

In [33]:
#Feature 9 - min y-axis value
y_min = (np.amin(datay, axis = 1)).T 
y_min

array([0., 0., 0., ..., 0., 0., 0.])

In [34]:
#Feature 10 - min z-axis value
z_min = (np.amin(dataz, axis = 1)).T 
z_min

array([-75.61229137, -95.51368341, -96.09745095, ..., -60.45296723,
       -57.74738138, -68.57960379])

In [35]:
#Feature 11 - max x-axis value
x_max = (np.amax(datax, axis = 1)).T 
x_max

array([ 89.99802253,  48.78046722,  79.04487197, ..., 114.1044535 ,
        74.95006865,  93.48507021])

In [36]:
#Feature 12 - max y-axis value
y_max = (np.amax(datay, axis = 1)).T 
y_max

array([ 88.67727892, 137.1762527 , 132.025198  , ..., 148.4059994 ,
       100.7451192 , 151.3174329 ])

In [37]:
#Feature 13 - maz z-axis value
z_max = (np.amax(dataz, axis = 1)).T 
z_max

array([ 0.        ,  0.        ,  7.82026413, ..., 13.03395624,
        0.        ,  4.27686864])

In [38]:
#Saving the features as a CSV file
df = pd.DataFrame({'xmean': x_mean, 'ymean': y_mean, 'zmean': z_mean, 'xstd': x_std, 'ystd': y_std, 'zstd': z_std, 'xmax': x_max, 'ymax':y_max, 'zmax': z_max,'xmin':x_min, 'ymin':y_min, 'zmin':z_min, 'num': number, 'Class': Class })
df.to_csv('linearTrain.csv')

Repeating this for the test dataset

In [39]:
#Separating the X, Y and Z axis data
datax = raw_test[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11']]
datay = raw_test[['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10', 'Y11']]
dataz = raw_test[['Z0', 'Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'Z7', 'Z8', 'Z9', 'Z10', 'Z11']]
Class = raw_test['Class']

datax = np.array(datax)
datay = np.array(datay)
dataz = np.array(dataz)
Class = np.array(Class)

In [40]:
#Replacing the cells with no entries with 0
datax = np.nan_to_num(datax)
datay = np.nan_to_num(datay)
dataz = np.nan_to_num(dataz)

In [41]:
datax[0:10]

array([[50.43080478, 12.83191885, 42.39951634, 47.61809086, 70.52226988,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [49.18760449, 12.01510186, 46.34979993, 41.76299865, 70.84056741,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [48.70960357,  8.88630861, 40.71185145, 69.60267089, 45.81233278,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [13.48247884, 48.61881545, 38.67935584, 45.82635018, 67.46918963,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [60.5664457 , 14.24364582, 47.72182173, 39.868457  , 46.16591647,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [60.96939861, 11.81564069, 41.12797069, 48.3283752 , 46.38530399,
         0.        ,  

In [42]:
datax.shape

(21099, 12)

In [43]:
datay[0:10]

array([[ 4.29629197, 82.79346438, 76.40269297, 42.91149628, 65.1890302 ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 4.61569853, 83.00536659, 43.43540618, 76.52460578, 64.93112048,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 4.75096046, 84.24406388, 76.98511108, 65.49123022, 43.75547823,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [81.8508535 ,  4.47354348, 77.64648907, 43.1282062 , 66.36919587,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [69.58336141, 81.5607829 ,  4.8360266 , 76.97572582, 43.25630328,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [69.89064816, 83.16411899, 76.91676708,  5.30332621, 43.92380663,
         0.        ,  

In [44]:
datay.shape

(21099, 12)

In [45]:
dataz[0:10]

array([[-80.13064242, -43.60871486, -48.35159325, -97.04299657,
        -51.54404222,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-81.05524239, -44.30655193, -97.801319  , -48.80231238,
        -51.25110131,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-81.3528225 , -45.91818228, -49.27801711, -52.20011274,
        -98.08775676,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-42.69402633, -81.42178274, -50.68172529, -98.21334106,
        -53.74673421,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-58.21400775, -41.92133726, -81.92370468, -49.48035749,
        -97.50433961,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [-57.5506181 , -42.95776881,

In [46]:
dataz.shape

(21099, 12)

In [47]:
x_mean = []
y_mean = []
z_mean = []
x_std = []
y_std = []
z_std = []
number = []

for i in range (len(datax)):
  x_mean.append(np.mean(datax[i]))
  y_mean.append(np.mean(datay[i]))
  z_mean.append(np.mean(dataz[i]))
  x_std.append(np.std(datax[i]))
  y_std.append(np.std(datay[i]))
  z_std.append(np.std(dataz[i]))
  number.append(np.count_nonzero([datax[i], datay[i], dataz[i]]))

In [48]:
#Feature 1 - mean of x-axis values
x_mean = np.array(x_mean) 
x_mean

array([18.65021673, 18.34633936, 17.81023061, ..., 23.41970386,
       16.98669585, 23.51120051])

In [49]:
#Feature 2 - mean of y-axis values
y_mean = np.array(y_mean) 
y_mean

array([22.63274798, 22.7093498 , 22.93557032, ..., 80.79464181,
       78.04153726, 80.7871236 ])

In [50]:
#Feature 3 - mean of z-axis values
z_mean = np.array(z_mean) 
z_mean

array([-26.72316578, -26.93471058, -27.23640762, ..., -24.77923359,
       -21.13030303, -24.87805937])

In [51]:
#Feature 4 - standard deviation of x-axis values
x_std = np.array(x_std) 
x_std

array([25.12062452, 24.89237349, 24.57284522, ..., 37.63943907,
       34.13224391, 37.60711556])

In [52]:
#Feature 5 - standard deviation of y-axis values
y_std = np.array(y_std) 
y_std

array([32.47396157, 32.50810276, 32.8348135 , ..., 45.59415791,
       49.1834747 , 45.72780854])

In [53]:
#Feature 6 - standard deviation of z-axis values
z_std = np.array(z_std) 
z_std

array([34.35733405, 34.64188016, 34.87989053, ..., 24.85758926,
       24.90258098, 24.94971577])

In [54]:
#Feature 7 - number of data points present
number = np.array(number) 
number

array([15, 15, 15, ..., 30, 27, 30])

In [55]:
#Feature 8 - min x-axis value
x_min = (np.amin(datax, axis = 1)).T 
x_min

array([  0.        ,   0.        ,   0.        , ..., -30.2256749 ,
       -30.0845882 , -30.03140158])

In [56]:
#Feature 9 - min y-axis value
y_min = (np.amin(datay, axis = 1)).T 
y_min

array([0., 0., 0., ..., 0., 0., 0.])

In [57]:
#Feature 10 - min z-axis value
z_min = (np.amin(dataz, axis = 1)).T 
z_min

array([-97.04299657, -97.801319  , -98.08775676, ..., -62.71873546,
       -63.22162593, -63.02657442])

In [58]:
#Feature 11 - max x-axis value
x_max = (np.amax(datax, axis = 1)).T 
x_max

array([70.52226988, 70.84056741, 69.60267089, ..., 88.2910287 ,
       88.46570937, 88.34744742])

In [59]:
#Feature 12 - max y-axis value
y_max = (np.amax(datay, axis = 1)).T 
y_max

array([ 82.79346438,  83.00536659,  84.24406388, ..., 135.60590286,
       135.52392926, 135.76292171])

In [60]:
#Feature 13 - maz z-axis value
z_max = (np.amax(dataz, axis = 1)).T 
z_max

array([ 0.        ,  0.        ,  0.        , ..., 11.02034689,
       10.81495719, 11.1078565 ])

In [61]:
#Saving the features as a CSV file
df = pd.DataFrame({'xmean': x_mean, 'ymean': y_mean, 'zmean': z_mean, 'xstd': x_std, 'ystd': y_std, 'zstd': z_std, 'xmax': x_max, 'ymax':y_max, 'zmax': z_max,'xmin':x_min, 'ymin':y_min, 'zmin':z_min, 'num': number, 'Class': Class })
df.to_csv('linearTest.csv')